// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImProtocol.proto

package org.zhongweixian.live.protocol;

/**
 * <pre>
 **
 * 聊天类型
 * </pre>
 *
 * Protobuf enum {@code src.main.proto.ChatType}
 */
public enum ChatType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *普通单聊，支持是否阅读
   * </pre>
   *
   * <code>CHAT_TYPE_PUBLIC = 0;</code>
   */
  CHAT_TYPE_PUBLIC(0),
  /**
   * <pre>
   *私密单聊，读后即毁
   * </pre>
   *
   * <code>CHAT_TYPE_PRIVATE = 1;</code>
   */
  CHAT_TYPE_PRIVATE(1),
  /**
   * <pre>
   *普通群聊  (显示阅读数，可以结合http协议来做)
   * </pre>
   *
   * <code>CHAT_TYPE_GROUP = 2;</code>
   */
  CHAT_TYPE_GROUP(2),
  /**
   * <pre>
   *私密群聊，读后即毁
   * </pre>
   *
   * <code>CHAT_TYPE_GROUP_PRIVATE = 3;</code>
   */
  CHAT_TYPE_GROUP_PRIVATE(3),
  /**
   * <pre>
   *系统消息
   * </pre>
   *
   * <code>CHAT_SYSTEM = 4;</code>
   */
  CHAT_SYSTEM(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *普通单聊，支持是否阅读
   * </pre>
   *
   * <code>CHAT_TYPE_PUBLIC = 0;</code>
   */
  public static final int CHAT_TYPE_PUBLIC_VALUE = 0;
  /**
   * <pre>
   *私密单聊，读后即毁
   * </pre>
   *
   * <code>CHAT_TYPE_PRIVATE = 1;</code>
   */
  public static final int CHAT_TYPE_PRIVATE_VALUE = 1;
  /**
   * <pre>
   *普通群聊  (显示阅读数，可以结合http协议来做)
   * </pre>
   *
   * <code>CHAT_TYPE_GROUP = 2;</code>
   */
  public static final int CHAT_TYPE_GROUP_VALUE = 2;
  /**
   * <pre>
   *私密群聊，读后即毁
   * </pre>
   *
   * <code>CHAT_TYPE_GROUP_PRIVATE = 3;</code>
   */
  public static final int CHAT_TYPE_GROUP_PRIVATE_VALUE = 3;
  /**
   * <pre>
   *系统消息
   * </pre>
   *
   * <code>CHAT_SYSTEM = 4;</code>
   */
  public static final int CHAT_SYSTEM_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChatType valueOf(int value) {
    return forNumber(value);
  }

  public static ChatType forNumber(int value) {
    switch (value) {
      case 0: return CHAT_TYPE_PUBLIC;
      case 1: return CHAT_TYPE_PRIVATE;
      case 2: return CHAT_TYPE_GROUP;
      case 3: return CHAT_TYPE_GROUP_PRIVATE;
      case 4: return CHAT_SYSTEM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChatType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
          public ChatType findValueByNumber(int number) {
            return ChatType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.zhongweixian.live.protocol.ImProtocol.getDescriptor()
        .getEnumTypes().get(3);
  }

  private static final ChatType[] VALUES = values();

  public static ChatType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChatType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:src.main.proto.ChatType)
}

