// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImProtocol.proto

package org.zhongweixian.live.protocol;

public final class ImProtocol {
  private ImProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_LoginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ImProtocol.proto\022\016src.main.proto\"\225\001\n\014L" +
      "oginMessage\022$\n\003cmd\030\001 \001(\0162\027.src.main.prot" +
      "o.Command\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030" +
      "\003 \001(\t\022.\n\ndeviceType\030\004 \001(\0162\032.src.main.pro" +
      "to.DeviceType\022\013\n\003cts\030\005 \001(\003*b\n\nDeviceType" +
      "\022\022\n\016DEVICE_TYPE_H5\020\000\022\022\n\016DEVICE_TYPE_PC\020\001" +
      "\022\027\n\023DEVICE_TYPE_ANDROID\020\002\022\023\n\017DEVICE_TYPE" +
      "_IOS\020\003*\234\004\n\007Command\022\r\n\tCMD_LOGIN\020\000\022\022\n\016CMD" +
      "_LOGIN_RESP\020\001\022\014\n\010CMD_PING\020\002\022\014\n\010CMD_AUTH\020" +
      "\003\022\024\n\020CMD_SEND_SUCCESS\020\004\022\022\n\016CMD_JOIN_GROU",
      "P\020\005\022\032\n\026CMD_JOIN_GROUP_MANAGER\020\006\022\031\n\025CMD_J" +
      "OIN_GROUP_NOTIFY\020\007\022\031\n\025CMD_EXIT_GROUP_NOT" +
      "IFY\020\010\022\022\n\016CMD_GROUP_CHAT\020\t\022\033\n\027CMD_GROUP_C" +
      "HAT_SECURITY\020\n\022\014\n\010CMD_CHAT\020\013\022\025\n\021CMD_CHAT" +
      "_SECURITY\020\014\022\027\n\023CMD_TALK_LIST_CLOSE\020\r\022\022\n\016" +
      "CMD_CANCEL_MSG\020\016\022\027\n\023CMD_CANCEL_MSG_RESP\020" +
      "\017\022\025\n\021CMD_GET_USER_INFO\020\020\022\032\n\026CMD_GET_USER" +
      "_INFO_RESP\020\021\022\022\n\rCMD_TALK_LIST\020\310\001\022\027\n\022CMD_" +
      "TALK_LIST_RESP\020\311\001\022\022\n\rCMD_USER_INFO\020\312\001\022\027\n" +
      "\022CMD_USER_INFO_RESP\020\313\001\022\023\n\016CMD_GROUP_INFO",
      "\020\314\001\022\030\n\023CMD_GROUP_INFO_RESP\020\315\001*\320\001\n\017JoinGr" +
      "oupResult\022\034\n\030JOIN_GROUP_RESULT_UNKNOW\020\000\022" +
      "\030\n\024JOIN_GROUP_RESULT_OK\020\001\022\037\n\033JOIN_GROUP_" +
      "RESULT_NOT_EXIST\020\002\022 \n\034JOIN_GROUP_RESULT_" +
      "GROUP_FULL\020\003\022!\n\035JOIN_GROUP_RESULT_IN_BAC" +
      "KLIST\020\004\022\037\n\033JOIN_GROUP_RESULT_TAKEOUTED\020\005" +
      "*z\n\010ChatType\022\024\n\020CHAT_TYPE_PUBLIC\020\000\022\025\n\021CH" +
      "AT_TYPE_PRIVATE\020\001\022\023\n\017CHAT_TYPE_GROUP\020\002\022\033" +
      "\n\027CHAT_TYPE_GROUP_PRIVATE\020\003\022\017\n\013CHAT_SYST" +
      "EM\020\004*\254\001\n\007MsgType\022\021\n\rMSG_TYPE_TEXT\020\000\022\020\n\014M",
      "SG_TYPE_IMG\020\001\022\022\n\016MSG_TYPE_VOICE\020\002\022\022\n\016MSG" +
      "_TYPE_VIDEO\020\003\022\022\n\016MSG_TYPE_MUSIC\020\004\022\021\n\rMSG" +
      "_TYPE_NEWS\020\005\022\024\n\020MSG_TYPE_PERSION\020\006\022\027\n\023MS" +
      "G_TYPE_JOIN_GROUP\020\007B%\n\036org.zhongweixian." +
      "live.protocolP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_src_main_proto_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_src_main_proto_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_LoginMessage_descriptor,
        new java.lang.String[] { "Cmd", "Username", "Password", "DeviceType", "Cts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
