// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImProtocol.proto

package org.zhongweixian.live.protocol;

/**
 * Protobuf type {@code src.main.proto.LoginMessage}
 */
public  final class LoginMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:src.main.proto.LoginMessage)
    LoginMessageOrBuilder {
  // Use LoginMessage.newBuilder() to construct.
  private LoginMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginMessage() {
    cmd_ = 0;
    username_ = "";
    password_ = "";
    deviceType_ = 0;
    cts_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LoginMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            cmd_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            deviceType_ = rawValue;
            break;
          }
          case 40: {

            cts_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zhongweixian.live.protocol.ImProtocol.internal_static_src_main_proto_LoginMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zhongweixian.live.protocol.ImProtocol.internal_static_src_main_proto_LoginMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zhongweixian.live.protocol.LoginMessage.class, org.zhongweixian.live.protocol.LoginMessage.Builder.class);
  }

  public static final int CMD_FIELD_NUMBER = 1;
  private int cmd_;
  /**
   * <code>optional .src.main.proto.Command cmd = 1;</code>
   */
  public int getCmdValue() {
    return cmd_;
  }
  /**
   * <code>optional .src.main.proto.Command cmd = 1;</code>
   */
  public org.zhongweixian.live.protocol.Command getCmd() {
    org.zhongweixian.live.protocol.Command result = org.zhongweixian.live.protocol.Command.valueOf(cmd_);
    return result == null ? org.zhongweixian.live.protocol.Command.UNRECOGNIZED : result;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>optional string username = 2;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>optional string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>optional string password = 3;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>optional string password = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETYPE_FIELD_NUMBER = 4;
  private int deviceType_;
  /**
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  public int getDeviceTypeValue() {
    return deviceType_;
  }
  /**
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  public org.zhongweixian.live.protocol.DeviceType getDeviceType() {
    org.zhongweixian.live.protocol.DeviceType result = org.zhongweixian.live.protocol.DeviceType.valueOf(deviceType_);
    return result == null ? org.zhongweixian.live.protocol.DeviceType.UNRECOGNIZED : result;
  }

  public static final int CTS_FIELD_NUMBER = 5;
  private long cts_;
  /**
   * <code>optional int64 cts = 5;</code>
   */
  public long getCts() {
    return cts_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cmd_ != org.zhongweixian.live.protocol.Command.CMD_LOGIN.getNumber()) {
      output.writeEnum(1, cmd_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (deviceType_ != org.zhongweixian.live.protocol.DeviceType.DEVICE_TYPE_H5.getNumber()) {
      output.writeEnum(4, deviceType_);
    }
    if (cts_ != 0L) {
      output.writeInt64(5, cts_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cmd_ != org.zhongweixian.live.protocol.Command.CMD_LOGIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, cmd_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (deviceType_ != org.zhongweixian.live.protocol.DeviceType.DEVICE_TYPE_H5.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, deviceType_);
    }
    if (cts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, cts_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zhongweixian.live.protocol.LoginMessage)) {
      return super.equals(obj);
    }
    org.zhongweixian.live.protocol.LoginMessage other = (org.zhongweixian.live.protocol.LoginMessage) obj;

    boolean result = true;
    result = result && cmd_ == other.cmd_;
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && deviceType_ == other.deviceType_;
    result = result && (getCts()
        == other.getCts());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + cmd_;
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + deviceType_;
    hash = (37 * hash) + CTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCts());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.live.protocol.LoginMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zhongweixian.live.protocol.LoginMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code src.main.proto.LoginMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:src.main.proto.LoginMessage)
      org.zhongweixian.live.protocol.LoginMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhongweixian.live.protocol.ImProtocol.internal_static_src_main_proto_LoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhongweixian.live.protocol.ImProtocol.internal_static_src_main_proto_LoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhongweixian.live.protocol.LoginMessage.class, org.zhongweixian.live.protocol.LoginMessage.Builder.class);
    }

    // Construct using org.zhongweixian.live.protocol.LoginMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cmd_ = 0;

      username_ = "";

      password_ = "";

      deviceType_ = 0;

      cts_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zhongweixian.live.protocol.ImProtocol.internal_static_src_main_proto_LoginMessage_descriptor;
    }

    public org.zhongweixian.live.protocol.LoginMessage getDefaultInstanceForType() {
      return org.zhongweixian.live.protocol.LoginMessage.getDefaultInstance();
    }

    public org.zhongweixian.live.protocol.LoginMessage build() {
      org.zhongweixian.live.protocol.LoginMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.zhongweixian.live.protocol.LoginMessage buildPartial() {
      org.zhongweixian.live.protocol.LoginMessage result = new org.zhongweixian.live.protocol.LoginMessage(this);
      result.cmd_ = cmd_;
      result.username_ = username_;
      result.password_ = password_;
      result.deviceType_ = deviceType_;
      result.cts_ = cts_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zhongweixian.live.protocol.LoginMessage) {
        return mergeFrom((org.zhongweixian.live.protocol.LoginMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zhongweixian.live.protocol.LoginMessage other) {
      if (other == org.zhongweixian.live.protocol.LoginMessage.getDefaultInstance()) return this;
      if (other.cmd_ != 0) {
        setCmdValue(other.getCmdValue());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.deviceType_ != 0) {
        setDeviceTypeValue(other.getDeviceTypeValue());
      }
      if (other.getCts() != 0L) {
        setCts(other.getCts());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zhongweixian.live.protocol.LoginMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zhongweixian.live.protocol.LoginMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int cmd_ = 0;
    /**
     * <code>optional .src.main.proto.Command cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>optional .src.main.proto.Command cmd = 1;</code>
     */
    public Builder setCmdValue(int value) {
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .src.main.proto.Command cmd = 1;</code>
     */
    public org.zhongweixian.live.protocol.Command getCmd() {
      org.zhongweixian.live.protocol.Command result = org.zhongweixian.live.protocol.Command.valueOf(cmd_);
      return result == null ? org.zhongweixian.live.protocol.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .src.main.proto.Command cmd = 1;</code>
     */
    public Builder setCmd(org.zhongweixian.live.protocol.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      cmd_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .src.main.proto.Command cmd = 1;</code>
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private int deviceType_ = 0;
    /**
     * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
     */
    public int getDeviceTypeValue() {
      return deviceType_;
    }
    /**
     * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
     */
    public Builder setDeviceTypeValue(int value) {
      deviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
     */
    public org.zhongweixian.live.protocol.DeviceType getDeviceType() {
      org.zhongweixian.live.protocol.DeviceType result = org.zhongweixian.live.protocol.DeviceType.valueOf(deviceType_);
      return result == null ? org.zhongweixian.live.protocol.DeviceType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
     */
    public Builder setDeviceType(org.zhongweixian.live.protocol.DeviceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      deviceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
     */
    public Builder clearDeviceType() {
      
      deviceType_ = 0;
      onChanged();
      return this;
    }

    private long cts_ ;
    /**
     * <code>optional int64 cts = 5;</code>
     */
    public long getCts() {
      return cts_;
    }
    /**
     * <code>optional int64 cts = 5;</code>
     */
    public Builder setCts(long value) {
      
      cts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 cts = 5;</code>
     */
    public Builder clearCts() {
      
      cts_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:src.main.proto.LoginMessage)
  }

  // @@protoc_insertion_point(class_scope:src.main.proto.LoginMessage)
  private static final org.zhongweixian.live.protocol.LoginMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zhongweixian.live.protocol.LoginMessage();
  }

  public static org.zhongweixian.live.protocol.LoginMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginMessage>
      PARSER = new com.google.protobuf.AbstractParser<LoginMessage>() {
    public LoginMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginMessage> getParserForType() {
    return PARSER;
  }

  public org.zhongweixian.live.protocol.LoginMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

