// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImProtocol.proto

package org.zhongweixian.live.protocol;

public interface LoginMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.LoginMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .src.main.proto.Command cmd = 1;</code>
   */
  int getCmdValue();
  /**
   * <code>optional .src.main.proto.Command cmd = 1;</code>
   */
  org.zhongweixian.live.protocol.Command getCmd();

  /**
   * <code>optional string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  int getDeviceTypeValue();
  /**
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  org.zhongweixian.live.protocol.DeviceType getDeviceType();

  /**
   * <code>optional int64 cts = 5;</code>
   */
  long getCts();
}
